
import { serve } from "https://deno.land/std@0.168.0/http/server.ts"
import Replicate from "https://esm.sh/replicate@0.25.2"

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers":
    "authorization, x-client-info, apikey, content-type",
};

interface ImageGenerationRequest {
  prompt: string;
  input_image: string;
  aspect_ratio: string;
  width: number;
  height: number;
}

// Helper function to clamp and normalize dimensions
const normalizeDimensions = (width: number, height: number): { width: number; height: number } => {
  // Clamp to allowed range
  const clampedWidth = Math.max(256, Math.min(2048, width));
  const clampedHeight = Math.max(256, Math.min(2048, height));
  
  // Round to nearest multiple of 8 for better model compatibility
  const normalizedWidth = Math.round(clampedWidth / 8) * 8;
  const normalizedHeight = Math.round(clampedHeight / 8) * 8;
  
  return { width: normalizedWidth, height: normalizedHeight };
};

const validateRequest = (body: any): { isValid: boolean; errors: string[] } => {
  const errors: string[] = [];
  
  if (!body.prompt || typeof body.prompt !== 'string' || body.prompt.trim().length === 0) {
    errors.push("prompt is required and must be a non-empty string");
  }
  
  if (!body.input_image || typeof body.input_image !== 'string') {
    errors.push("input_image is required and must be a string");
  }
  
  if (!body.aspect_ratio || typeof body.aspect_ratio !== 'string') {
    errors.push("aspect_ratio is required and must be a string");
  }
  
  if (!body.width || typeof body.width !== 'number' || body.width <= 0) {
    errors.push("width is required and must be a positive number");
  }
  
  if (!body.height || typeof body.height !== 'number' || body.height <= 0) {
    errors.push("height is required and must be a positive number");
  }

  // Validate aspect ratio values
  const validAspectRatios = [
    "match_input_image", "1:1", "16:9", "21:9", "3:2", "2:3", 
    "4:5", "5:4", "3:4", "4:3", "9:16", "9:21"
  ];
  
  if (body.aspect_ratio && !validAspectRatios.includes(body.aspect_ratio)) {
    errors.push(`aspect_ratio must be one of: ${validAspectRatios.join(', ')}`);
  }

  // Note: We no longer validate strict dimension limits here as we'll normalize them

  return { isValid: errors.length === 0, errors };
};

serve(async (req) => {
  // Handle CORS preflight requests
  if (req.method === 'OPTIONS') {
    return new Response('ok', { headers: corsHeaders })
  }

  try {
    const REPLICATE_API_KEY = Deno.env.get('REPLICATE_API_KEY')
    if (!REPLICATE_API_KEY) {
      throw new Error('REPLICATE_API_KEY is not set')
    }

    const replicate = new Replicate({
      auth: REPLICATE_API_KEY,
    })

    const body = await req.json()
    console.log("Received request body keys:", Object.keys(body))

    // Validate request
    const validation = validateRequest(body);
    if (!validation.isValid) {
      console.error("Validation errors:", validation.errors);
      return new Response(
        JSON.stringify({ 
          error: "Validation failed",
          details: validation.errors
        }), {
          headers: { ...corsHeaders, 'Content-Type': 'application/json' },
          status: 400,
        }
      )
    }

    const requestData: ImageGenerationRequest = body as ImageGenerationRequest;

    // Normalize dimensions to ensure they're within valid range
    const normalizedDimensions = normalizeDimensions(requestData.width, requestData.height);
    console.log(`Original dimensions: ${requestData.width}x${requestData.height}`);
    console.log(`Normalized dimensions: ${normalizedDimensions.width}x${normalizedDimensions.height}`);

    console.log("Generating image with Flux Kontext Dev")
    console.log("Prompt:", requestData.prompt)
    console.log("Aspect ratio:", requestData.aspect_ratio)
    console.log("Width:", normalizedDimensions.width)
    console.log("Height:", normalizedDimensions.height)
    
    const input = {
      prompt: requestData.prompt,
      go_fast: false, // Changed from true to false for better quality
      guidance: 4.0, // Increased from 2.5 to 4.0 for better prompt adherence
      input_image: requestData.input_image,
      aspect_ratio: requestData.aspect_ratio,
      output_format: "png", // Changed from "jpg" to "png" for lossless quality
      output_quality: 95, // Increased from 80 to 95 for higher quality
      num_inference_steps: 44 // Increased from 30 to 44 for better detail
    };

    console.log("Final input to Replicate:", input);

    const output = await replicate.run("black-forest-labs/flux-kontext-dev", { input });

    console.log("Generation successful")
    
    // Ensure output is always an array for consistent frontend handling
    const outputArray = Array.isArray(output) ? output : [output];
    
    // Validate output
    if (!outputArray || outputArray.length === 0) {
      throw new Error("No images were generated by the model");
    }

    return new Response(JSON.stringify({ 
      success: true,
      output: outputArray,
      message: "Image generated successfully with Flux Kontext Dev",
      metadata: {
        prompt: requestData.prompt,
        aspect_ratio: requestData.aspect_ratio,
        dimensions: {
          width: normalizedDimensions.width,
          height: normalizedDimensions.height
        }
      }
    }), {
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      status: 200,
    })

  } catch (error) {
    console.error("Error in function:", error)
    
    // Provide more specific error messages
    let errorMessage = "An unexpected error occurred";
    let statusCode = 500;
    
    if (error.message?.includes("REPLICATE_API_KEY")) {
      errorMessage = "Service configuration error";
      statusCode = 503;
    } else if (error.message?.includes("Validation")) {
      errorMessage = error.message;
      statusCode = 400;
    } else if (error.message?.includes("rate limit")) {
      errorMessage = "Service temporarily unavailable due to rate limiting";
      statusCode = 429;
    } else if (error.message?.includes("timeout")) {
      errorMessage = "Request timed out, please try again";
      statusCode = 408;
    }
    
    return new Response(JSON.stringify({ 
      error: errorMessage,
      details: error.toString(),
      timestamp: new Date().toISOString()
    }), {
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      status: statusCode,
    })
  }
})
