// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ouwckceemghbfqyineij.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im91d2NrY2VlbWdoYmZxeWluZWlqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE2ODYwNjUsImV4cCI6MjA2NzI2MjA2NX0.st9Ju-OrAWX44a57D75G_2tmpE-IcNDXDYGHfDo12VE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});